// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkeRe2gVMPWhxoGs08ffe8tZvtzFH0W0g',
    appId: '1:359516470236:web:6c237757f3c729497d6d19',
    messagingSenderId: '359516470236',
    projectId: 'studybrain-4a176',
    authDomain: 'studybrain-4a176.firebaseapp.com',
    storageBucket: 'studybrain-4a176.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkeRe2gVMPWhxoGs08ffe8tZvtzFH0W0g',
    appId: '1:359516470236:android:app_id_here',
    messagingSenderId: '359516470236',
    projectId: 'studybrain-4a176',
    storageBucket: 'studybrain-4a176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkeRe2gVMPWhxoGs08ffe8tZvtzFH0W0g',
    appId: '1:359516470236:ios:app_id_here',
    messagingSenderId: '359516470236',
    projectId: 'studybrain-4a176',
    storageBucket: 'studybrain-4a176.firebasestorage.app',
    iosBundleId: 'com.studybrain.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkeRe2gVMPWhxoGs08ffe8tZvtzFH0W0g',
    appId: '1:359516470236:ios:app_id_here',
    messagingSenderId: '359516470236',
    projectId: 'studybrain-4a176',
    storageBucket: 'studybrain-4a176.firebasestorage.app',
    iosBundleId: 'com.studybrain.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkeRe2gVMPWhxoGs08ffe8tZvtzFH0W0g',
    appId: '1:359516470236:web:6c237757f3c729497d6d19',
    messagingSenderId: '359516470236',
    projectId: 'studybrain-4a176',
    authDomain: 'studybrain-4a176.firebaseapp.com',
    storageBucket: 'studybrain-4a176.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAkeRe2gVMPWhxoGs08ffe8tZvtzFH0W0g',
    appId: '1:359516470236:web:6c237757f3c729497d6d19',
    messagingSenderId: '359516470236',
    projectId: 'studybrain-4a176',
    authDomain: 'studybrain-4a176.firebaseapp.com',
    storageBucket: 'studybrain-4a176.firebasestorage.app',
  );
}